[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/coming-soon"
  to = "/coming-soon.html"
  status = 200

[[headers]]
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/coming-soon"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/coming-soon.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
